version: "3"

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=serasa
      - POSTGRES_PASSWORD=serasa
      - POSTGRES_DB=reddit
    ports:
      - "5432:5432"
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "5433:80"
    depends_on:
      - postgres